# Generated by Django 4.1.3 on 2022-11-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('tg_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tg_nick', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=100)),
                ('account_balance', models.FloatField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('logs', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dispatcher',
            fields=[
                ('tg_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tg_nick', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('account_balance', models.FloatField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('logs', models.TextField(blank=True)),
            ],
        ),
    ]
